### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by mweibel** [rokka-io/rokka.js#14]
Write tests against a mock API, probably. 

- Make sure to test especially the create sourceimage call

**Comment by pstadler** [comment]
We should think about simply stubbing requests and check for correct headers, url, payload, et. al as the Rokka API server is private and we don't do anythings with responses.

- Stub requests
- Mock edge cases (errors, file streams, etc.)
- Decide whether to run tests in a browser, on a server, or both

**Comment by mweibel** [comment]
Yeah, you're right. Thought about also testing the responses but we're not doing anything with them, so let's just test that we're sending the right thing. 

Edge cases: Retries should be also tested, IMO. 
Where to run: both! And test in all major browsers.. Which may be a pain to setup, let's see how to do that.

**Comment by pstadler** [comment]
So the current coverage is around 80% with #26. Let's close this issue.

Follow up is #27, but this is not required for the 1.0.0 release in my opinion.
