### ISSUE TITLE
sourceimages.create with metadata fails

### ISSUE THREAD

**Issue by dulnan** [rokka-io/rokka.js#45]
Calling sourceimages.create and passing metadata (meta_user) results in:

`TypeError: source.on is not a function`

Figured out this happens because the value of property `'meta_user[0]'` in `formData` is an object. The request module then defines this as `application/octet-stream`, where it then later tries to attach an stream event listener to it, which is not possible.

For now, this can be fixed by using JSON.stringify on the meta_user property's value before passing it to sourceimages.create.

```javascript
const metadata = {
  meta_user: JSON.stringify({
    myMetaField: 'myValue'
  })
};
```

**Comment by chregu** [comment]
mmmh. I guess it's also maybe a documentation issue. But that one is definitely wrong (at least the example, which even has PHP delimiters in it ;)). I guess we could fix that with BC in mind, when we stringify it, when it's an object and leave it, when it's a string.
