### ISSUE TITLE
Replace request with something smaller

### ISSUE THREAD

**Issue by chregu** [rokka-io/rokka.js#59]
The request package seems to be huge
```
$ npx package-size request
  package         size     minified  gzipped
  request@2.88.0  2.47 MB  1.05 MB   309.3 KB
```

we should replace it with for example `axios`. 
```
$ npx package-size axios
  package       size      minified  gzipped
  axios@0.19.0  68.26 KB  14.59 KB  4.81 KB
```

Any opinions on this? @mweibel maybe?

**Comment by mweibel** [comment]
Is since a long time on my list, yes ;) 
Axios is an option, but I'd actually use [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) via something like [`cross-fetch`](https://github.com/lquixada/cross-fetch) (ponyfill, not polyfill) to ensure it works accross browser and node.js. 
```
$ npx package-size cross-fetch
  package            size      minified  gzipped
  cross-fetch@3.0.4  16.64 KB  8.38 KB   2.71 KB
```
It's even smaller, plus the benefit that when using ponyfill it won't be included if used in modern browsers (well, depends on the buildchain, but anyway).

**Comment by chregu** [comment]
cross-fetch sounds also like a good idea and based on some standard.

The next question then would be: We do just pass through the response object from `request` to the enduser. `fetch` (and `axios`) do have a different format.

3 solutions:
1) Total BC break (new major release), just pass through the `fetch` response object, lots of work for people using it, since it's quite different

2) Half BC break (but also new major release). We emulate most often used properties from the `request` response (mainly `body`, but also `status`, `statusMessage`). Also provide a way to access the original `fetch` Response. Users of the libraries will have an easier way to upgrade, but there might still be BC problems ('thus the major versions)

3) No BC break. Totally be compatible to the old object. Don't think this is very feasible or worth it.

I'd vote for 2, but maybe I'm missing something.

**Comment by mweibel** [comment]
I'd also go for version 2. I think that should work and is also not too bad to not return the raw response object since we know what kind of response we get, usually.

**Comment by chregu** [comment]
Ok, I'll take that approach and try with 'cross-fetch'

First results are promising:
with current rokka from my little vue app:
```
  File                                    Size              Gzipped
  dist/js/chunk-vendors.066bd83f.js       1487.43 KiB       464.88 KiB
```
with `cross-fetch`
```
  File                                    Size              Gzipped
  dist/js/chunk-vendors.de5e8025.js       331.82 KiB        108.14 KiB
```
seems worth it ;)

**Comment by chregu** [comment]
So, there's a first alpha version in #60 
The dashboard and my app seem to work fine with it. Missing is the retry stuff

**Comment by chregu** [comment]
#60 was merged yesterday, close this issue
